### ISSUE TITLE
downloaded maps of 'Hong Kong' and 'Macao' and 'China' are identical?

### ISSUE THREAD

**Issue by treee111** [treee111/wahooMapsCreator#11]
And I found another thing that 'Hong Kong' and 'Macao' are as same as China's map data, the tool downloaded 3 exactly same size file with diff filenames.

from: #10

**Comment by Ebe66** [comment]
Hi, this is intended behavior. Wahoo uses China, Hong Kong and Macao, geofabrik includes/sees those as just China.
Or put differently, Geofarik has no region for Hong Kong.
So get Hong Kong I chose to redownload the geofabrik map that contains it.
Other, better, solutions would be to make local copies of the file instead of redownloading it or even better "map" the name Hong Kong to the downloaded China map file. There are more countries where I do the same, you can find the list at Translate_Country = {

**Comment by treee111** [comment]
Hi @Ebe66 (ebo in google groups?) for clarification!

We could check if the requested mapfile is already downloaded and up-to-date somehow.
Maybe checking by processing e.g. Hong Kong, if China or Macao have already be downloaded (using the Translate_Country array) and use the same filename for all three countries.

**Comment by treee111** [comment]
Hi @assofour, in the meantime I implemented your question / feature request :)
