### ISSUE TITLE
Option to create multiple countries in one run

### ISSUE THREAD

**Issue by bin101** [treee111/wahooMapsCreator#189]
It would be nice to be able to create multiple countries in one run without duplicated map files.

Currently I create countries one by one with border countries and the during copy overwrite already existing map files.

**Comment by treee111** [comment]
Hi, thanks for the feature request!
Creating more than one country in one call can be implemented.

Two questions to understand it better:
- Is the main benefit from your point of view that exaclty the same "border-country-tiles" are not processed two times and you'll have speed improvements?
- Do you use wahooMapsCreator using CLI or GUI?
- CLI would be easier to implement imho, would that suit you?

**Comment by bin101** [comment]
- exactly and for the benefit to not reschedule every country after finishing one
- currently GUI but CLI would be sufficient enough ;)

By the way is there a example  setup to generate the routing tiles with valhalla/mjolnir based on the OSM data in the meantime? The docs links are already outdated but it seems some user was able to use it:
https://my.hidrive.com/share/1t65k1b0lb#$/Windows-Wahoo-Map-Creator-Osmosis-v2-Maps

**Comment by treee111** [comment]
👍  you are right, letting it run at its own for multiple countries is also a benefit!

for my own memories a commit which does provide multiple countries via an extra argument - there have been others working for this it seams ;-).
https://github.com/ThaBaur/wahooMapsCreator/commit/f0a6d564f1afe63f275e360b81c626e23c4f115a
I might do it another way round, I'll see.

@Ebe66 was able to use generate routing files. He uploads the stuff to the HiDrive and there are routing tiles up if I am right.
In a thread on a roadbike forum is a discussion about routing tiles going on actually. Might be a starter point for you?
https://www.rennrad-news.de/forum/threads/aktuelles-kartenmaterial-f%C3%BCr-wahoo-elemnt-bolt-roam-elemnt-selbst-generieren.175315/page-19#post-5655169 

I did not go into that until now. Because my BOLTv1 can't use them and this repo is taking enought time I will not dig into generating routing tiles in the next months

**Comment by Ebe66** [comment]
@bin101 I still use my own "predecessor" to @treee111 's version which does not have a GUI :-) 
I myself simply use batch files to generate continents at a time. And just for the reason you mention I do NOT discard the generated tiles after the completion of a country but use the temp storage as a "tile cache" if you will. Certainly when doing multiple countries in a run it saves time.

Generating routing tiles is a relatively simple but time and resource consuming thing. As you can find in the forum link from treee111 I use this for it https://github.com/gis-ops/docker-valhalla I run it on openstreetmaps planet files because it is totally unclear to me what happens at border regions when you use country files for it and there is as far as I know no way to "look into" the generated files. I have just finished a run and am creating the zip files from them atm. They should be up on the hidrive in the next couple of days. Docker memory usage when generating them peaks at around 40+GB (that I have seen) and takes about 3 days with lots of ssd space. In the forum discussion you will find something about differences in routing between the ~2 year old Wahoo files and my files. As there is very little to configure on the routing tile creation side of things is assume this is because of changes made in the source osm maps but I don't know (yet) how to look at more then a single history version of a way back on osm. The gpx track sent to me follows the road instead of the cycleway. If you (on a pc) select car it does provide his desired 1ste exit at the roundabout. If you switch to bike routing that instruction is missing simply because the cycleway offers no other option.

**Comment by bin101** [comment]
@Ebe66 Nice to know. Your maps contain the same data as generated here by default settings?

**Comment by Ebe66** [comment]
@bin101 no, not entirely but pretty close. My maps contain more POI's (useful or not decide for yourself, you don't have to display them). Take a look at the bottom of the example vtm-elemnt.xml file on the hidrive or my github. There probably will be some other small differences. 
The/a way to look at it is that a guy named Henk made a first proto version of the map creator for linux. Me being on windows wanted to make my own maps so I made my own version. Treee111 took that code and took it from the 16th to the 21ste century :-) He also had some input from others (Zenziwerken for example) from who I also borrowed idea's. So the end products are "close" to each other but not 100% identical.

**Comment by treee111** [comment]
Hi @bin101,
I implemented the feature request in the linked PR. Could you please test if it works for you.
I made the development based on v4.0.0 branch so you need to create a new Anaconda environment with python 3.10.

You need to take these steps to test:
1. create a new environment
If you create the environment using another name than your existing environment, you do not have to delete the existing one.
https://github.com/treee111/wahooMapsCreator/blob/release-v4.0.0/docs/QUICKSTART_ANACONDA.md#create-anaconda-environment
2. Install alpha version of wahooMapsCreator
~~`pip install wahoomc==4.0.0a2`~~
~~`pip install wahoomc==4.0.0a4`~~
~~`pip install wahoomc==4.0.0a6`~~
`pip install wahoomc==4.0.0a9`
3. Test it
`python -m wahoomc cli -co malta,liechtenstein` or any other multiple countries separated by comma ;-)

**Comment by treee111** [comment]
implemented via #190
