### ISSUE TITLE
waterway=stream is missing in tags-to-keep.json

### ISSUE THREAD

**Issue by HalloMike** [treee111/wahooMapsCreator#200]
Hi,
Wahoo does not show streams (OSM-Tag: waterway=stream).
Datafill in tag-wahoo-poi.xml is correct.

Issue is in tags-to-keep.json.
The entry for stream is missing between Line 80-85.

## Current
```
        "waterway": [
            "canal",
            "drain",
            "river",
            "riverbank"
        ],
```

## Expected
```
       "waterway": [
            "canal",
            "stream",
            "drain",
            "river",
            "riverbank"
        ],

```

Thanks
Mike

**Comment by treee111** [comment]
Hi @HalloMike,
thanks for your hint! Both files are not 100 % identical. In tag-wahoo-poi.xml there might be more OSM objects then kept in the map by tags-to-keep.json. That does not hurt and so this is no bug.

Because I think this is useful I integrated waterway/stream into the standard delivered tags-to-keep.json with #201.

You can always adjust these both files to your needs locally on your computer. See documentation here: https://github.com/treee111/wahooMapsCreator/blob/develop/docs/USAGE.md#user-specific-configuration
